### ISSUE TITLE
syosetu no longer importing

### ISSUE THREAD

**Issue by andrewdzik** [safirex/WNovelArchiver#20]
**Describe the bug**
There are errors for downloading novels from syosetu.  It looks like they changed their formatting and the importer is no longer able to correctly find the html elements.  

**To Reproduce**
Try to download a novel from syosetu, got error:

Traceback (most recent call last):
  File "\WNovelArchiver-master\archive_updater.py", line 149, in <module>
    parser()
  File "\WNovelArchiver-master\archive_updater.py", line 143, in parser
    print(args.func(args))
  File "\WNovelArchiver-master\archive_updater.py", line 94, in option_update
    archiveUpdate(findNovel(regex),keep_text_format)
  File "\WNovelArchiver-master\src\main_functions.py", line 50, in archiveUpdate
    novel.processNovel()
  File "\WNovelArchiver-master\src\Downloaders.py", line 514, in processNovel
    self.processTocResume(html)
  File "\WNovelArchiver-master\src\Downloaders.py", line 537, in processTocResume
    string = 'novel title= ' + self.getNovelTitle(html) + '\n\n'
  File "\WNovelArchiver-master\src\Downloaders.py", line 563, in getNovelTitle
    return writer[0]
IndexError: list index out of range

I tried changing that line 563 to match the current format,
writer = re.findall(r'\<h1 class="p-novel__title">(.*?)\</h1\>', html) 
and that fixed that part, but then more parts broke due to other formatting changes on their site, and I was not able to get it working on my own.

**Expected behavior**
Able to download novels successfully.  This is a really great tool when it is working!

**Comment by safirex** [comment]
yeah, syosetu added pagination that broke the parsers. 
i may do it within this week otherwise just find another tool

**Comment by safirex** [comment]
[@a66d1d3](https://github.com/safirex/WNovelArchiver/commit/a66d1d3405994549555944095f69d6049c889ff2) should fix your issue (for syosetu only, please give up using kakuyomu with this tool).
update the project and you should be good.

**Comment by andrewdzik** [comment]
Thanks for your quick work!  That seems to fix it for syosetu in general, but while testing using your default input.txt I saw that novel18.syosetu.com still has the same error as before.  I think you have separate code for handling it.  Would it be possible to fix that also?

**Comment by safirex** [comment]
the last commit should have fixed the issues on syosetu and novel18

**Comment by andrewdzik** [comment]
That fixed it!  Happy new years.

**Comment by andrewdzik** [comment]
Marking this as fixed.
