### ISSUE TITLE
Kakuyomu download dont work always

### ISSUE THREAD

**Issue by MasterGeo0X** [safirex/WNovelArchiver#8]
I found this weird bug, when trying to download this novel

https://kakuyomu.jp/works/16816452219449457673

I got no chapters, and the download ends.

I have downloaded from others kakuyomu links and not have any problem, its just this one link i got nothing,
things i tried
-updating the pips
-changing folders
-changing the "name" parameter in the input,txt
-leaving the "name" parameter blank
-wipe the novel list folder 
-make the respective folder manually
and nothing i just got this

C:\WNovelArchiver>python archive_updater.py d
Namespace(mode='d')
downloading
16816452219449457673;

C:\WNovelArchiver>

**Comment by safirex** [comment]
the pattern to recognize kakyomu novels didn't work on the most recent ones because they added a digit, code has been updated, should work fine now

**Comment by MasterGeo0X** [comment]
Thx for your great work!
