### ISSUE TITLE
Bug:missing words when Japanese novel using emphasis marks

### ISSUE THREAD

**Issue by miodaibuki** [safirex/WNovelArchiver#9]
**Describe the bug**
emphasis marks in japanese(dots above words) lead to word missing

**To Reproduce**
example: https://kakuyomu.jp/works/16816452219814758602/episodes/16816452219847612555  (１４．図書館)
last few lines
raw:"...というわけではなさそうですね」...(middle context)...【会話を続ける】ことが発動条件となるものもあります」"
【】means emphasis marks

outcome:"というわけではなさそうですね」
<span>会</span><span>話</span><span>を</span><span>続</span><span>け</span><span>る</span></em>ことが発動条件となるものもあります」"

(middle context) disappeared. And those<span></span> are annoying 

**Expected behavior**
thanks for your work:) It would be perfect without this bug

**Comment by safirex** [comment]
I believe da97f45b42b419ef89ce7512a2cbc0dbfa7491fa fixed the problem

**Comment by miodaibuki** [comment]
> I believe [da97f45](https://github.com/safirex/WNovelArchiver/commit/da97f45b42b419ef89ce7512a2cbc0dbfa7491fa) fixed the problem

but we miss those emphasis marks now :(

**Comment by safirex** [comment]
ok so 3e3e6a7845d210f28e7c117ad49cfca2681114fe add a parser argument, if you launch with `-md`, it will keep the html tags and register the file as .md (markdown), (you can find free md readers here and there).
as an example for the new argument: `py archive_updater.py u -md` to update novels as .md files, it also works for download but only on kakyomu novels (it might also change syosetu novels file extension but the content won't change from the .txt ones)
